name: CI Phase2

run-name: CI Phase2

on: workflow_dispatch

permissions:
  contents: write
  pull-requests: write

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  GIT_USER_EMAIL: "41898282+github-actions[bot]@users.noreply.github.com"
  GIT_USER_NAME: "github-actions[bot]"

jobs:
  test-new-issue:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        branch: [main, develop, v1]
    steps:
      - name: Generate a token
        id: generate_token
        uses: actions/create-github-app-token@v1
        with:
          app-id: ${{ secrets.APP_ID }}
          private-key: ${{ secrets.PRIVATE_KEY }}

      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ steps.generate_token.outputs.token }}

      - run: |
          git config --local user.name $GIT_USER_NAME
          git config --local user.email $GIT_USER_EMAIL
          git checkout test/${{ matrix.os }}/${{ matrix.branch }}/new-issue
          git revert -n HEAD
          git commit --author="$GIT_USER_NAME <$GIT_USER_EMAIL>" -m "$(date +%s) ${{ matrix.os }}/${{ matrix.branch }}"
          git commit --allow-empty -m "$(date +%s) ${{ matrix.os }}/${{ matrix.branch }}"
          git push origin test/${{ matrix.os }}/${{ matrix.branch }}/new-issue

  test-max-issue:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    strategy:
      matrix:
        os: [ubuntu-latest]
        branch: [main, develop, v1]
    steps:
      - name: Generate a token
        id: generate_token
        uses: actions/create-github-app-token@v1
        with:
          app-id: ${{ secrets.APP_ID }}
          private-key: ${{ secrets.PRIVATE_KEY }}

      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ steps.generate_token.outputs.token }}

      - run: |
          git config --local user.name $GIT_USER_NAME
          git config --local user.email $GIT_USER_EMAIL
          git checkout test/${{ matrix.os }}/${{ matrix.branch }}/max-issue
          git revert -n HEAD
          git commit --author="$GIT_USER_NAME <$GIT_USER_EMAIL>" -m "$(date +%s) ${{ matrix.os }}/${{ matrix.branch }}"
          git commit --allow-empty -m "$(date +%s) ${{ matrix.os }}/${{ matrix.branch }}"
          git push origin test/${{ matrix.os }}/${{ matrix.branch }}/max-issue

  test-summary:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    strategy:
      matrix:
        os: [ubuntu-latest]
        branch: [main, develop, v1]
    steps:
      - name: Generate a token
        id: generate_token
        uses: actions/create-github-app-token@v1
        with:
          app-id: ${{ secrets.APP_ID }}
          private-key: ${{ secrets.PRIVATE_KEY }}

      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ steps.generate_token.outputs.token }}

      - run: |
          git config --local user.name $GIT_USER_NAME
          git config --local user.email $GIT_USER_EMAIL
          git checkout test/${{ matrix.os }}/${{ matrix.branch }}/summary-head
          git revert -n HEAD
          git commit --author="$GIT_USER_NAME <$GIT_USER_EMAIL>" -m "$(date +%s) ${{ matrix.os }}/${{ matrix.branch }}"
          git commit --allow-empty -m "$(date +%s) ${{ matrix.os }}/${{ matrix.branch }}"
          git push origin test/${{ matrix.os }}/${{ matrix.branch }}/summary-head

  danger-new-issue:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    strategy:
      matrix:
        os: [ubuntu-latest]
        branch: [main]
    steps:
      - name: Generate a token
        id: generate_token
        uses: actions/create-github-app-token@v1
        with:
          app-id: ${{ secrets.APP_ID }}
          private-key: ${{ secrets.PRIVATE_KEY }}

      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ steps.generate_token.outputs.token }}

      - run: |
          git config --local user.name $GIT_USER_NAME
          git config --local user.email $GIT_USER_EMAIL
          git checkout danger/${{ matrix.os }}/${{ matrix.branch }}/new-issue
          git revert -n HEAD
          git commit --author="$GIT_USER_NAME <$GIT_USER_EMAIL>" -m "$(date +%s) ${{ matrix.os }}/${{ matrix.branch }}"
          git commit --allow-empty -m "$(date +%s) ${{ matrix.os }}/${{ matrix.branch }}"
          git push origin danger/${{ matrix.os }}/${{ matrix.branch }}/new-issue

  # invertase-new-issue:
  #   runs-on: ubuntu-latest
  #   timeout-minutes: 30
  #   strategy:
  #     matrix:
  #       os: [ubuntu-latest]
  #       branch: [main]
  #   steps:
  #     - name: Generate a token
  #       id: generate_token
  #       uses: actions/create-github-app-token@v1
  #       with:
  #         app-id: ${{ secrets.APP_ID }}
  #         private-key: ${{ secrets.PRIVATE_KEY }}

  #     - uses: actions/checkout@v4
  #       with:
  #         fetch-depth: 0
  #         token: ${{ steps.generate_token.outputs.token }}

  #     - run: |
  #         git config --local user.name $GIT_USER_NAME
  #         git config --local user.email $GIT_USER_EMAIL
  #         git checkout invertase/${{ matrix.os }}/${{ matrix.branch }}/new-issue
  #         git revert -n HEAD
  #         git commit --author="$GIT_USER_NAME <$GIT_USER_EMAIL>" -m "$(date +%s) ${{ matrix.os }}/${{ matrix.branch }}"
  #         git commit --allow-empty -m "$(date +%s) ${{ matrix.os }}/${{ matrix.branch }}"
  #         git push origin invertase/${{ matrix.os }}/${{ matrix.branch }}/new-issue
