name: CI Phase1

run-name: CI Phase1

on: workflow_dispatch

permissions:
  contents: write
  pull-requests: write

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  GIT_USER_EMAIL: "41898282+github-actions[bot]@users.noreply.github.com"
  GIT_USER_NAME: "github-actions[bot]"

jobs:
  clean-branches:
    uses: ./.github/workflows/clean.yml
    secrets: inherit

  test-new-issue:
    needs: clean-branches
    runs-on: ubuntu-latest
    timeout-minutes: 30
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        branch: [main, develop, v1]
    steps:
      - name: Generate a token
        id: generate_token
        uses: actions/create-github-app-token@v1
        with:
          app-id: ${{ secrets.APP_ID }}
          private-key: ${{ secrets.PRIVATE_KEY }}

      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ steps.generate_token.outputs.token }}

      - env:
          GITHUB_TOKEN: ${{ steps.generate_token.outputs.token }}
        run: |
          git config --local user.name $GIT_USER_NAME
          git config --local user.email $GIT_USER_EMAIL
          git checkout -b test/${{ matrix.os }}/${{ matrix.branch }}/new-issue origin/_template/new-issue
          git commit --amend --author="$GIT_USER_NAME <$GIT_USER_EMAIL>" -m "$(date +%s) ${{ matrix.os }}/${{ matrix.branch }}"
          git push origin test/${{ matrix.os }}/${{ matrix.branch }}/new-issue
          gh pr create --base main --head test/${{ matrix.os }}/${{ matrix.branch }}/new-issue --title "test/${{ matrix.os }}/${{ matrix.branch }}/issue" --body "test/${{ matrix.os }}/${{ matrix.branch }}/Issue"

  test-max-issue:
    needs: clean-branches
    runs-on: ubuntu-latest
    timeout-minutes: 30
    strategy:
      matrix:
        os: [ubuntu-latest]
        branch: [main, develop, v1]
    steps:
      - name: Generate a token
        id: generate_token
        uses: actions/create-github-app-token@v1
        with:
          app-id: ${{ secrets.APP_ID }}
          private-key: ${{ secrets.PRIVATE_KEY }}

      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ steps.generate_token.outputs.token }}

      - env:
          GITHUB_TOKEN: ${{ steps.generate_token.outputs.token }}
        run: |
          git config --local user.name $GIT_USER_NAME
          git config --local user.email $GIT_USER_EMAIL
          git checkout -b test/${{ matrix.os }}/${{ matrix.branch }}/max-issue origin/_template/max-issue
          git commit --amend --author="$GIT_USER_NAME <$GIT_USER_EMAIL>" -m "$(date +%s) ${{ matrix.os }}/${{ matrix.branch }}"
          git push origin test/${{ matrix.os }}/${{ matrix.branch }}/max-issue
          gh pr create --base main --head test/${{ matrix.os }}/${{ matrix.branch }}/max-issue --title "test/${{ matrix.os }}/${{ matrix.branch }}/max-issue" --body "test/${{ matrix.os }}/${{ matrix.branch }}/max-issue"

  # test-no-issue:
  #   needs: clean-branches
  #   runs-on: ubuntu-latest
  #   timeout-minutes: 30
  #   strategy:
  #     matrix:
  #       os: [ubuntu-latest, windows-latest, macos-latest]
  #       branch: [main, develop, v1]
  #   steps:
  #     - uses: actions/checkout@v4
  #       with:
  #         fetch-depth: 0

  #     - env:
  #         GH_TOKEN: ${{ secrets.GH_PAT }}
  #       run: |
  #         git checkout -b test/${{ matrix.os }}/${{ matrix.branch }}/no-issue origin/_template/no-issue
  #         git config --local user.name $GIT_USER_NAME
  #         git config --local user.email $GIT_USER_EMAIL
  #         git commit --amend -m "$(date +%s) ${{ matrix.os }}/${{ matrix.branch }}"
  #         git push origin test/${{ matrix.os }}/${{ matrix.branch }}/no-issue
  #         gh pr create --base main --head test/${{ matrix.os }}/${{ matrix.branch }}/no-issue --title "test/${{ matrix.os }}/${{ matrix.branch }}/no-issue" --body "test/${{ matrix.os }}/${{ matrix.branch }}/no-issue"

  test-summary:
    needs: clean-branches
    runs-on: ubuntu-latest
    timeout-minutes: 30
    strategy:
      matrix:
        os: [ubuntu-latest]
        branch: [main, develop, v1]
    steps:
      - name: Generate a token
        id: generate_token
        uses: actions/create-github-app-token@v1
        with:
          app-id: ${{ secrets.APP_ID }}
          private-key: ${{ secrets.PRIVATE_KEY }}

      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ steps.generate_token.outputs.token }}

      - env:
          GITHUB_TOKEN: ${{ steps.generate_token.outputs.token }}
        run: |
          git config --local user.name $GIT_USER_NAME
          git config --local user.email $GIT_USER_EMAIL
          git checkout -b test/${{ matrix.os }}/${{ matrix.branch }}/summary-head origin/_template/summary-head
          git commit --amend --author="$GIT_USER_NAME <$GIT_USER_EMAIL>" -m "$(date +%s) ${{ matrix.os }}/${{ matrix.branch }}"
          git push origin test/${{ matrix.os }}/${{ matrix.branch }}/summary-head
          gh pr create --base _template/summary-base --head test/${{ matrix.os }}/${{ matrix.branch }}/summary-head --title "test/${{ matrix.os }}/${{ matrix.branch }}/summary" --body "test/${{ matrix.os }}/${{ matrix.branch }}/summary"

  danger-test-new-issue:
    needs: clean-branches
    runs-on: ubuntu-latest
    timeout-minutes: 30
    strategy:
      matrix:
        os: [ubuntu-latest]
        branch: [main]
    steps:
      - name: Generate a token
        id: generate_token
        uses: actions/create-github-app-token@v1
        with:
          app-id: ${{ secrets.APP_ID }}
          private-key: ${{ secrets.PRIVATE_KEY }}

      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ steps.generate_token.outputs.token }}

      - env:
          GITHUB_TOKEN: ${{ steps.generate_token.outputs.token }}
        run: |
          git config --local user.name $GIT_USER_NAME
          git config --local user.email $GIT_USER_EMAIL
          git checkout -b danger/${{ matrix.os }}/${{ matrix.branch }}/new-issue origin/_template/new-issue
          git commit --amend --author="$GIT_USER_NAME <$GIT_USER_EMAIL>" -m "$(date +%s) ${{ matrix.os }}/${{ matrix.branch }}"
          git push origin danger/${{ matrix.os }}/${{ matrix.branch }}/new-issue
          gh pr create --base main --head danger/${{ matrix.os }}/${{ matrix.branch }}/new-issue --title "danger/${{ matrix.os }}/${{ matrix.branch }}/issue" --body "danger/${{ matrix.os }}/${{ matrix.branch }}/issue"

  # invertase-test-new-issue:
  #   needs: clean-branches
  #   runs-on: ubuntu-latest
  #   timeout-minutes: 30
  #   strategy:
  #     matrix:
  #       os: [ubuntu-latest]
  #       branch: [main]
  #   steps:
  #     - name: Generate a token
  #       id: generate_token
  #       uses: actions/create-github-app-token@v1
  #       with:
  #         app-id: ${{ secrets.APP_ID }}
  #         private-key: ${{ secrets.PRIVATE_KEY }}

  #     - uses: actions/checkout@v4
  #       with:
  #         fetch-depth: 0
  #         token: ${{ steps.generate_token.outputs.token }}

  #     - env:
  #         GITHUB_TOKEN: ${{ steps.generate_token.outputs.token }}
  #       run: |
  #         git config --local user.name $GIT_USER_NAME
  #         git config --local user.email $GIT_USER_EMAIL
  #         git checkout -b invertase/${{ matrix.os }}/${{ matrix.branch }}/new-issue origin/_template/new-issue
  #         git commit --amend --author="$GIT_USER_NAME <$GIT_USER_EMAIL>" -m "$(date +%s) ${{ matrix.os }}/${{ matrix.branch }}"
  #         git push origin invertase/${{ matrix.os }}/${{ matrix.branch }}/new-issue
  #         gh pr create --base main --head invertase/${{ matrix.os }}/${{ matrix.branch }}/new-issue --title "[invertase/${{ matrix.os }}/${{ matrix.branch }}] Issue" --body "[danger/${{ matrix.os }}/${{ matrix.branch }}] Issue"
