name: CI Phase2

run-name: CI Phase2

on: workflow_dispatch

permissions:
  contents: write
  pull-requests: write

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  GIT_USER_EMAIL: "41898282+github-actions[bot]@users.noreply.github.com"
  GIT_USER_NAME: "github-actions[bot]"

jobs:
  test-new-issue:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        branch: [main, develop, v1]
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ secrets.GH_PAT }}

      - run: |
          git checkout test/${{ matrix.os }}/${{ matrix.branch }}/new-issue
          git config --local user.name $GIT_USER_NAME
          git config --local user.email $GIT_USER_EMAIL
          git revert -n HEAD
          git commit -m "$(date +%s) ${{ matrix.os }}/${{ matrix.branch }}"
          git commit --allow-empty -m "$(date +%s) ${{ matrix.os }}/${{ matrix.branch }}"
          git push origin test/${{ matrix.os }}/${{ matrix.branch }}/new-issue

  test-max-issue:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        branch: [main, develop, v1]
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ secrets.GH_PAT }}

      - run: |
          git checkout test/${{ matrix.os }}/${{ matrix.branch }}/max-issue
          git config --local user.name $GIT_USER_NAME
          git config --local user.email $GIT_USER_EMAIL
          git revert -n HEAD
          git commit -m "$(date +%s) ${{ matrix.os }}/${{ matrix.branch }}"
          git commit --allow-empty -m "$(date +%s) ${{ matrix.os }}/${{ matrix.branch }}"
          git push origin test/${{ matrix.os }}/${{ matrix.branch }}/max-issue

  test-summary:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        branch: [main, develop, v1]
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ secrets.GH_PAT }}

      - run: |
          git checkout test/${{ matrix.os }}/${{ matrix.branch }}/summary-head
          git config --local user.name $GIT_USER_NAME
          git config --local user.email $GIT_USER_EMAIL
          git revert -n HEAD
          git commit -m "$(date +%s) ${{ matrix.os }}/${{ matrix.branch }}"
          git commit --allow-empty -m "$(date +%s) ${{ matrix.os }}/${{ matrix.branch }}"
          git push origin test/${{ matrix.os }}/${{ matrix.branch }}/summary-head
