name: clean-branches

run-name: Clean branches

on: workflow_dispatch

permissions:
  contents: write
  pull-requests: write

jobs:
  delete-branches:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
      - name: Delete branches
        uses: actions/github-script@v7
        with:
          script: |
            const pattern = /^(test|danger)\//;
            const branches = await github.rest.repos.listBranches({
              owner: context.repo.owner,
              repo: context.repo.repo,
            });
            for (const branch of branches.data) {
              console.log(`Checking branch: ${branch.name}`);
              if (pattern.test(branch.name)) {
                await github.rest.git.deleteRef({
                  owner: context.repo.owner,
                  repo: context.repo.repo,
                  ref: `heads/${branch.name}`,
                });
                console.log(`Deleted branch: ${branch.name}`);
              }
            }
