name: test

run-name: test

on: pull_request

permissions:
  contents: read
  pull-requests: write
  issues: write
  statuses: write

jobs:
  ubuntu-main:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    if: ${{ contains(github.head_ref, 'main') && contains(github.head_ref, 'ubuntu-latest') }}
    steps:
      - uses: actions/checkout@v4

      - uses: subosito/flutter-action@v2
        with:
          flutter-version: ${{ (vars.FLUTTER_VERSION != null && vars.FLUTTER_VERSION) || '' }}
          channel: stable
          cache: true

      - run: flutter pub get

      - run: flutter analyze --write=flutter_analyze.log || true

      - uses: yorifuji/flutter-analyze-commenter@main
        if: ${{ !cancelled() }}
        with:
          analyze_log: flutter_analyze.log
          verbose: true

  ubuntu-develop:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    if: ${{ contains(github.head_ref, 'develop') && contains(github.head_ref, 'ubuntu-latest') }}
    steps:
      - uses: actions/checkout@v4

      - uses: subosito/flutter-action@v2
        with:
          flutter-version: ${{ (vars.FLUTTER_VERSION != null && vars.FLUTTER_VERSION) || '' }}
          channel: stable
          cache: true

      - run: flutter pub get

      - run: flutter analyze --write=flutter_analyze.log || true

      - uses: yorifuji/flutter-analyze-commenter@develop
        if: ${{ !cancelled() }}
        with:
          analyze_log: flutter_analyze.log
          verbose: true

  ubuntu-v1:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    if: ${{ contains(github.head_ref, 'ubuntu-latest') && contains(github.head_ref, 'v1') }}
    steps:
      - uses: actions/checkout@v4

      - uses: subosito/flutter-action@v2
        with:
          flutter-version: ${{ (vars.FLUTTER_VERSION != null && vars.FLUTTER_VERSION) || '' }}
          channel: stable
          cache: true

      - run: flutter pub get

      - run: flutter analyze --write=flutter_analyze.log || true

      - uses: yorifuji/flutter-analyze-commenter@v1
        if: ${{ !cancelled() }}
        with:
          analyze_log: flutter_analyze.log
          verbose: true

  macos-main:
    runs-on: macos-latest
    timeout-minutes: 30
    if: ${{ contains(github.head_ref, 'main') && contains(github.head_ref, 'macos-latest') }}
    steps:
      - uses: actions/checkout@v4

      - uses: subosito/flutter-action@v2
        with:
          flutter-version: ${{ (vars.FLUTTER_VERSION != null && vars.FLUTTER_VERSION) || '' }}
          channel: stable
          cache: true

      - run: flutter pub get

      - run: flutter analyze --write=flutter_analyze.log || true

      - uses: yorifuji/flutter-analyze-commenter@main
        if: ${{ !cancelled() }}
        with:
          analyze_log: flutter_analyze.log
          verbose: true

  macos-develop:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    if: ${{ contains(github.head_ref, 'develop') && contains(github.head_ref, 'macos-latest') }}
    steps:
      - uses: actions/checkout@v4

      - uses: subosito/flutter-action@v2
        with:
          flutter-version: ${{ (vars.FLUTTER_VERSION != null && vars.FLUTTER_VERSION) || '' }}
          channel: stable
          cache: true

      - run: flutter pub get

      - run: flutter analyze --write=flutter_analyze.log || true

      - uses: yorifuji/flutter-analyze-commenter@develop
        if: ${{ !cancelled() }}
        with:
          analyze_log: flutter_analyze.log
          verbose: true

  macos-v1:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    if: ${{ contains(github.head_ref, 'macos-latest') && contains(github.head_ref, 'v1') }}
    steps:
      - uses: actions/checkout@v4

      - uses: subosito/flutter-action@v2
        with:
          flutter-version: ${{ (vars.FLUTTER_VERSION != null && vars.FLUTTER_VERSION) || '' }}
          channel: stable
          cache: true

      - run: flutter pub get

      - run: flutter analyze --write=flutter_analyze.log || true

      - uses: yorifuji/flutter-analyze-commenter@v1
        if: ${{ !cancelled() }}
        with:
          analyze_log: flutter_analyze.log
          verbose: true

  windows-main:
    runs-on: windows-latest
    timeout-minutes: 30
    if: ${{ contains(github.head_ref, 'windows-latest') && contains(github.head_ref, 'main') }}
    steps:
      - uses: actions/checkout@v4

      - uses: subosito/flutter-action@v2
        with:
          flutter-version: ${{ (vars.FLUTTER_VERSION != null && vars.FLUTTER_VERSION) || '' }}
          channel: stable
          cache: true

      - run: flutter pub get

      - run: flutter analyze --write=flutter_analyze.log || true

      - uses: yorifuji/flutter-analyze-commenter@main
        if: ${{ !cancelled() }}
        with:
          analyze_log: flutter_analyze.log
          verbose: true

  windows-develop:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    if: ${{ contains(github.head_ref, 'windows-latest') && contains(github.head_ref, 'develop') }}
    steps:
      - uses: actions/checkout@v4

      - uses: subosito/flutter-action@v2
        with:
          flutter-version: ${{ (vars.FLUTTER_VERSION != null && vars.FLUTTER_VERSION) || '' }}
          channel: stable
          cache: true

      - run: flutter pub get

      - run: flutter analyze --write=flutter_analyze.log || true

      - uses: yorifuji/flutter-analyze-commenter@develop
        if: ${{ !cancelled() }}
        with:
          analyze_log: flutter_analyze.log
          verbose: true

  windows-v1:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    if: ${{ contains(github.head_ref, 'windows-latest') && contains(github.head_ref, 'v1') }}
    steps:
      - uses: actions/checkout@v4

      - uses: subosito/flutter-action@v2
        with:
          flutter-version: ${{ (vars.FLUTTER_VERSION != null && vars.FLUTTER_VERSION) || '' }}
          channel: stable
          cache: true

      - run: flutter pub get

      - run: flutter analyze --write=flutter_analyze.log || true

      - uses: yorifuji/flutter-analyze-commenter@v1
        if: ${{ !cancelled() }}
        with:
          analyze_log: flutter_analyze.log
          verbose: true
