name: test

run-name: test

on:
  pull_request:
  workflow_dispatch:

permissions:
  contents: read
  pull-requests: write
  issues: write
  statuses: write

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  test-v1:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    if: ${{ startsWith(github.ref_name, 'test/v1') }}
    steps:
      - uses: actions/checkout@v4

      - uses: subosito/flutter-action@v2
        with:
          flutter-version: ${{ (vars.FLUTTER_VERSION != null && vars.FLUTTER_VERSION) || '' }}
          channel: stable
          cache: true

      - run: flutter pub get

      - run: flutter analyze --write=flutter_analyze.log || true

      - uses: yorifuji/flutter-analyze-commenter@v1
        if: ${{ !cancelled() }}
        with:
          analyze_log: flutter_analyze.log
          verbose: true

  test-develop:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    if: ${{ startsWith(github.ref_name, 'test/develop') }}
    steps:
      - uses: actions/checkout@v4

      - uses: subosito/flutter-action@v2
        with:
          flutter-version: ${{ (vars.FLUTTER_VERSION != null && vars.FLUTTER_VERSION) || '' }}
          channel: stable
          cache: true

      - run: flutter pub get

      - run: flutter analyze --write=flutter_analyze.log || true

      - uses: yorifuji/flutter-analyze-commenter@develop
        if: ${{ !cancelled() }}
        with:
          analyze_log: flutter_analyze.log
          verbose: true
